
#ifndef KEYPAD_CFG_H
#define KEYPAD_CFG_H

#define KEYPAD_MAX_NUM  2


#define KEYPAD0_INPUT_PIN_NUMS  4
#define KEYPAD0_OUTPUT_PIN_NUMS 4

#define KEYPAD1_INPUT_PIN_NUMS  6
#define KEYPAD1_OUTPUT_PIN_NUMS 3


#define KEYPAD_MAX_INPUT_PIN_NUMS  6
#define KEYPAD_MAX_OUTPUT_PIN_NUMS 4



#endif