#ifndef UART_CFG_H
#define UART_CFG_H

#define UART_SPEED       NORMAL_SPEED
#define CHARACTER_SIZE   DATA_8BIT
#define UART_MODE        ASYNC_MODE
#define PARITY_MODE      DISABLE
#define STOP_BIT_MODE    STOP_2BIT
#define CLOCK_POLARITY   FALLING_TX_RISING_RX


#endif
